// status code references:
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
// https://www.npmjs.com/package/http-status-codes#codes

const httpStatusCodes = {
  _100_CONTINUE: {code: 100, msg: "Continue"},
  _101_SWITCHING_PROTOCOLS: {code: 101, msg: "Switching Protocols"},
  _102_PROCESSING: {code: 102, msg: "Processing"},
  _200_OK: {code: 200, msg: "OK"},
  _201_CREATED: {code: 201, msg: "Created"},
  _202_ACCEPTED: {code: 202, msg: "Accepted"},
  _203_NON_AUTHORITATIVE_INFORMATION: {code: 203, msg: "Non Authoritative Information"},
  _204_NO_CONTENT: {code: 204, msg: "No Content"},
  _205_RESET_CONTENT: {code: 205, msg: "Reset Content"},
  _206_PARTIAL_CONTENT: {code: 206, msg: "Partial Content"},
  _207_MULTI_STATUS: {code: 207, msg: "Multi-Status"},
  _300_MULTIPLE_CHOICES: {code: 300, msg: "Multiple Choices"},
  _301_MOVED_PERMANENTLY: {code: 301, msg: "Moved Permanently"},
  _302_MOVED_TEMPORARILY: {code: 302, msg: "Moved Temporarily"},
  _303_SEE_OTHER: {code: 303, msg: "See Other"},
  _304_NOT_MODIFIED: {code: 304, msg: "Not Modified"},
  _305_USE_PROXY: {code: 305, msg: "Use Proxy"},
  _307_TEMPORARY_REDIRECT: {code: 307, msg: "Temporary Redirect"},
  _308_PERMANENT_REDIRECT: {code: 308, msg: "Permanent Redirect"},
  _400_BAD_REQUEST: {code: 400, msg: "Bad Request"},
  _401_UNAUTHORIZED: {code: 401, msg: "Unauthorized"},
  _402_PAYMENT_REQUIRED: {code: 402, msg: "Payment Required"},
  _403_FORBIDDEN: {code: 403, msg: "Forbidden"},
  _404_NOT_FOUND: {code: 404, msg: "Not Found"},
  _405_METHOD_NOT_ALLOWED: {code: 405, msg: "Method Not Allowed"},
  _406_NOT_ACCEPTABLE: {code: 406, msg: "Not Acceptable"},
  _407_PROXY_AUTHENTICATION_REQUIRED: {code: 407, msg: "Proxy Authentication Required"},
  _408_REQUEST_TIMEOUT: {code: 408, msg: "Request Timeout"},
  _409_CONFLICT: {code: 409, msg: "Conflict"},
  _410_GONE: {code: 410, msg: "Gone"},
  _411_LENGTH_REQUIRED: {code: 411, msg: "Length Required"},
  _412_PRECONDITION_FAILED: {code: 412, msg: "Precondition Failed"},
  _413_REQUEST_TOO_LONG: {code: 413, msg: "Request Entity Too Large"},
  _414_REQUEST_URI_TOO_LONG: {code: 414, msg: "Request-URI Too Long"},
  _415_UNSUPPORTED_MEDIA_TYPE: {code: 415, msg: "Unsupported Media Type"},
  _416_REQUESTED_RANGE_NOT_SATISFIABLE: {code: 416, msg: "Requested Range Not Satisfiable"},
  _417_EXPECTATION_FAILED: {code: 417, msg: "Expectation Failed"},
  _418_IM_A_TEAPOT: {code: 418, msg: "I'm a teapot"},
  _419_INSUFFICIENT_SPACE_ON_RESOURCE: {code: 419, msg: "Insufficient Space on Resource"},
  _420_METHOD_FAILURE: {code: 420, msg: "Method Failure"},
  _422_UNPROCESSABLE_ENTITY: {code: 422, msg: "Unprocessable Entity"},
  _423_LOCKED: {code: 423, msg: "Locked"},
  _424_FAILED_DEPENDENCY: {code: 424, msg: "Failed Dependency"},
  _428_PRECONDITION_REQUIRED: {code: 428, msg: "Precondition Required"},
  _429_TOO_MANY_REQUESTS: {code: 429, msg: "Too Many Requests"},
  _431_REQUEST_HEADER_FIELDS_TOO_LARGE: {code: 431, msg: "Request Header Fields Too Large"},
  _500_INTERNAL_SERVER_ERROR: {code: 500, msg: "Server Error"},
  _501_NOT_IMPLEMENTED: {code: 501, msg: "Not Implemented"},
  _502_BAD_GATEWAY: {code: 502, msg: "Bad Gateway"},
  _503_SERVICE_UNAVAILABLE: {code: 503, msg: "Service Unavailable"},
  _504_GATEWAY_TIMEOUT: {code: 504, msg: "Gateway Timeout"},
  _505_HTTP_VERSION_NOT_SUPPORTED: {code: 505, msg: "HTTP Version Not Supported"},
  _507_INSUFFICIENT_STORAGE: {code: 507, msg: "Insufficient Storage"},
  _511_NETWORK_AUTHENTICATION_REQUIRED: {code: 511, msg: "Network Authentication Required"},
};

module.exports = { 
  httpStatusCodes 
};